name: DeployToAWSS3

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -uses: action/checkout@main
      -uses: jakejarvis/s3-sync-action@main

       with:
         args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'

